### ISSUE TITLE
Good naming conventions

### ISSUE THREAD

**Issue by Albadylic** [fac-17/FFFF#182]
Particularly in [Select.hbs](https://github.com/fac-17/FFFF/blob/master/src/views/select.hbs) I noticed that your class names are readable and looks like you're trying to implement some BEM. Very impressive :1st_place_medal: 

The names for the data being taken from the query is not so clear though (e.g. `#each data` & `pname`). Perhaps you could give these more meaningful names. 

Great job though! :+1:

**Comment by gminova** [comment]
Thank you!
