### ISSUE TITLE
TEAM CODE OF CONDUCT

### ISSUE THREAD

**Issue by gminova** [fac-17/FFFF#3]
![code](https://user-images.githubusercontent.com/42014388/64213244-17c11900-cea4-11e9-8686-b63ab86aa96d.jpeg)

**Comment by andy-mc-donald** [comment]
## Revised code of conduct: 
-When you give feedback give a complement first 
-Continue to use SGC format when taking turns discussing issues
-If we're still debating a single issue after 5/10 mins we should each go round and give an opinion and then take a vote. 
-No vetos. The majority rules, and if it's split we ask a mentor to cast a deciding vote. 
-Strive to write the best possible code, but appreciate there is more than one way to solve a problem. If there is no clear functional reason for changing code that is written, leave it with review comments / suggestions. We can refactor messy (but functioning) code in week 2. 
-20 / 20 / 20 
-Changing pairs frequently
-Commit regularly

**Comment by samjam48** [comment]
i like this!

But what happened to daily walks. That idea was cool

**Comment by Albadylic** [comment]
Well done on re-writing the code of conduct! Seems like you're taking the time to make sure every member of the group is comfortable :star: :smile:
