### ISSUE TITLE
Naming convention in handlebars a bit confusing

### ISSUE THREAD

**Issue by samjam48** [fac-17/FFFF#92]
![image](https://user-images.githubusercontent.com/16625180/64859113-46b45900-d621-11e9-8137-67f7d635c9df.png)

At first I thought `this.sname` was a typo. but you also use "pname" and "cname" in other places.

This is rather inconsistent and confusing. I mean is `this.score` for a "score" element or for "core" element in "s" database??

**Comment by gminova** [comment]
this is because we use aliases for our db queries, :) it's what was recommended
